meta:
  url: "https://dddsydney2019.hbish.com"
  title: Are we there yet? Lesson learnt performance testing a crypto exchange API
  thumbnail:
  description: A talk about lessons in performance testing an crypto exchange API.
  sns:
    - twitter
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - javascript
      - scala
      - bash
      - rust
    plugins:
      - line-numbers
    theme: default
  chart: false
  math: false
extends:
  js: ./common/main.js
  css: ./style.css
  webpack: ./webpack.config.js
build:
  ssr: true
