meta:
  title: Are we there yet? Lesson learnt performance testing a crypto exchange API
  thumbnail:
  description: A talk about lessons in performance testing an crypto exchange API.
  sns:
    - twitter
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: true
  isVertical: false
  code:
    languages:
      - javascript
    plugins: []
    theme: default
  chart: false
  math: false
extends:
  js: ./common/main.js
  css: ./style.css
  webpack:
build:
  ssr: true
